/**
 * @fileoverview
 * @description
 * @license Apache-2.0
 * @author Yukiharu YABUKI <yabuki@netfort.gr.jp>
 * see LICENSE for details.
 */

// embed_files.ts
// このスクリプトは template.tar.gz を base64 文字列として埋め込みます。
import { decodeBase64, encodeBase64 } from "@std/encoding";

export function writeEmbbedfile(filePath: string, base64Content: string): void {
	// base64 文字列をデコードしてファイルに書き込む
	const decodedContent = decodeBase64(base64Content);
	console.log(`Writing file to ${filePath}`);
	Deno.writeFileSync(filePath, decodedContent, {
		createNew: true,
		append: false,
	});
}

// このファイルが直接実行された時にのみ処理を行う。import された場合は実行しない。
if (import.meta.main) {
	const templatePathAndFile: string = "../template.tar.gz";
	// template.tar.gz のパスを指定

	// ファイルを読み込み、base64 にエンコード
	const fileContent = Deno.readFileSync(templatePathAndFile);
	const base64Content = encodeBase64(fileContent);

	// TypeScript ファイルとして出力
	const outputPath = "./embeddedFiles.ts";
	const outputContent = `// embeddedFiles.ts
  // template.tar.gz を base64 文字列として埋め込んだファイル
  // This file is automatically generated by embed_files.ts.
  // Do not edit manually.
  
  export const embeddedFile = "${base64Content}";
  `;

	Deno.writeTextFileSync(outputPath, outputContent, {
		createNew: true,
		append: false,
	});
	console.log(`embeddedFiles.ts を生成しました: ${outputPath}`);
}
